---
- name: Build binary
  hosts: localhost
  gather_facts: false
  vars_files:
  - vars/main.yaml
  tasks:
  - name: Build binary
    import_tasks: tasks/build_binary.yaml

- name: Deploy dynamic-dns-service
  hosts: target
  become: true
  vars_files:
  - vars/main.yaml
  vars:
    service_name: dynamic-dns-service
  tasks:
  - name: Deploy service
    import_tasks: tasks/deploy_service.yaml
  handlers:
  - name: Reload systemd
    systemd:
      daemon_reload: yes
